name: gg_once_per_cycle
description: Use GgOncePerCycle to trigger tasks multiple times while ensuring they are only executed one time during a run loop cycle.
version: 1.3.2
homepage: https://github.com/inlavigo/gg_once_per_cycle
repository: https://github.com/inlavigo/gg_once_per_cycle

environment:
  sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  fake_async: ^1.1.0
  pana: ^0.22.2
  args: ^2.4.2
  gg_check: ^1.0.2
  gg_capture_print: ^1.0.2
